version: '2'
services:

  postgres:
    image: postgres:9.6.3
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alice
      - POSTGRES_PASSWORD=rabbithole
      - POSTGRES_DB=whiterabbit


  whiterabbit:
    build: .
    ports:
      - "5009:5009"
    volumes:
      - /home/ubuntu/bitcoin:/opt/bitcoin